coverage:
  status:
    default_rules:
      flag_coverage_not_uploaded_behavior: exclude
    project:
      web:
        target: auto
        threshold: 1%
      ui:
        target: auto
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default

component_management:
  individual_components:
    - component_id: ui
      name: "ui"
      paths:
        - packages/ui/**

    - component_id: web
      name: "web"
      paths:
        - apps/web/**
